### ISSUE TITLE
The 'exit without saving' is not working

### ISSUE THREAD

**Issue by soni-shashan** [clubgamma/Ticket-Booking#14]
### If you click `Exit without saving,` it will both exit and save the changes instead of discarding them.

**Comment by Meetpidev** [comment]
@soni-shashan The real problem is that after confirming the all details it is autometically save.. the functionally of exit without saving should be that if we select this then saved details should be removed(unsaved) and exit.. from sys..

**Comment by Meetpidev** [comment]
@soni-shashan is it right ?

**Comment by soni-shashan** [comment]
> @soni-shashan The real problem is that after confirming the all details it is autometically save.. the functionally of exit without saving should be that if we select this then saved details should be removed(unsaved) and exit.. from sys..

yes
