### ISSUE TITLE
 Implement 'Current Location' and Traveler Count Input for Accurate Price Calculation

### ISSUE THREAD

**Issue by soni-shashan** [clubgamma/Ticket-Booking#15]
### - Ask for Number of Travelers

**Comment by vasu-CE** [comment]
for this implementation current location is also from the indianCities array?

**Comment by soni-shashan** [comment]
### Yes, since we have 10 cities as destinations, our travel agency currently offers only these 10 Indian cities for travel: Delhi, Mumbai, Bangalore, Chennai, Kolkata, Hyderabad, Pune, Jaipur, Ahmedabad, and Lucknow. Therefore, the current location (pick-up point) is limited to these 10 cities.
