### ISSUE TITLE
Requested add lable of GSSoC (GirlScript Summer of Code)

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/Ticket-Booking#24]
I'm excited to contribute to this project! I'd like to request the addition of a label for GSSoC (GirlScript Summer of Code) to track and manage issues specifically related to this program.

Could you please:

1. Create a new label: GSSoC
2. Assign me to issues with this label, if possible

Thank you for considering my request!

**Comment by Meetpidev** [comment]
@soni-shashan Please mark label of hectoberfest-accepted if PR is successfully completed and merged...

**Comment by soni-shashan** [comment]
### @Meetpidev, this event is conducted by Club Gamma. You need to send a request to the club lead, @jalaym825.
