### ISSUE TITLE
Dynamic Ticket Selection and Booking

### ISSUE THREAD

**Issue by soni-shashan** [clubgamma/Ticket-Booking#3]
### Allow users to select the number of tickets, specify seat preferences, and enter customer details to complete the booking process.

**Comment by Meetpidev** [comment]
@soni-shashan My approch is that there is already predifined seates (E.g 100 ) user can select any seat from range 1-100.. suppose first user select seat no.1 then second user can not select the same seat.. for that we also have to display available seates so user can select seates easyly..
