### ISSUE TITLE
bug in category of ticket

### ISSUE THREAD

**Issue by vasu-CE** [clubgamma/Ticket-Booking#38]
when display the booking details and if we select VIP category it will show category: null
![Screenshot 2024-10-23 110448](https://github.com/user-attachments/assets/d9b5c559-8973-4087-8550-8017d3f4713b)

**Comment by Meetpidev** [comment]
@soni-shashan Problem in add booking function.. i resolved it and soon send you PR

**Comment by vasu-CE** [comment]
Resolved, i got it

**Comment by Meetpidev** [comment]
@vasu-CE Close this issue if you resolve it
