### ISSUE TITLE
 chat support system

### ISSUE THREAD

**Issue by soni-shashan** [clubgamma/Ticket-Booking#59]
### Implement a simple chat support system for users to get help with their bookings or ask questions.

**Comment by Meetpidev** [comment]
@soni-shashan In this who will give the answer the question ?? like if aksed question is that "this rout is cancelled or not ?" then who will answer this ?

**Comment by soni-shashan** [comment]
### create like faq section with an inbuilt question and answer

**Comment by vasu-CE** [comment]
assign
