### ISSUE TITLE
Issue in correct code

### ISSUE THREAD

**Issue by vasu-CE** [clubgamma/Ticket-Booking#75]
when user add the booking and print the summary of booking program will terminated
![image](https://github.com/user-attachments/assets/b5b2b2da-e8d2-4a75-a8b8-510aba69c1cd)

**Comment by vasu-CE** [comment]
and there is also one issue in the catagory you can see that all time booking.catagory[0] that is incorrect cause the catagory is string
![image](https://github.com/user-attachments/assets/2207b99d-e724-4cb9-9877-ca2a44c2347e)

**Comment by vasu-CE** [comment]
i solved both issue in one PR so please make level according to that

**Comment by soni-shashan** [comment]
> i solved both issue in one PR so please make level according to that

### you solved to bug so you get 4 points I give you 5 enjoy :)

**Comment by vasu-CE** [comment]
@soni-shashan Thanks
