### ISSUE TITLE
Don't ask for skip

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/Ticket-Booking#77]
In Modification, there is no option to skip no. of travelers.. there should be option to skip.. 

![Screenshot 2024-10-27 095608](https://github.com/user-attachments/assets/81521784-4e23-4e50-89de-026e2b10c31a)

**Comment by vasu-CE** [comment]
but what is needed to skip

**Comment by Meetpidev** [comment]
if someone wants to change only category.. then ? there should be skip option in it.. 

you are maybe thinking that we can enter same number of traveler if we dont want to change it...  if so then we should also remove skip option from previous options..... but its wrong.. we have to rewrite it..  so there should be skip option

**Comment by FireFistisDead** [comment]
@Meetpidev can you please elaborate i was not able to understand the use of skip statement

**Comment by Meetpidev** [comment]
@FireFistisDead 

### To allow users to change only the category, a "Skip" option should be included. This enables users to retain the same number of travelers without needing to modify it. Removing the "Skip" option from previous selections would be incorrect, as it provides flexibility in the process. Therefore, maintaining the "Skip" option is essential for a seamless user experience.

**Comment by FireFistisDead** [comment]
@Meetpidev got it!!
