### ISSUE TITLE
issue for mode transport

### ISSUE THREAD

**Issue by vasu-CE** [clubgamma/Ticket-Booking#85]
in this code all time is ask mode of transport there is wrong think that if we only see the booking what is needed so it is need in the add booking function 
![image](https://github.com/user-attachments/assets/843a6d4a-c94c-416a-b9ae-c9ec65e53fbf)

**Comment by Meetpidev** [comment]
### NO, we have to ask it first everytime.. so that based on the trasnport mode we can display the data...

**Comment by vasu-CE** [comment]
If i select 11 option Display FAQ what is need to select Bus or train
